#!/usr/bin/env bash

set -e

SRC_DIR=$(pwd)
BIN_DIR=$(cd "$(dirname "$0")"; pwd)

# Get the private IP of the dyno
export KONG_CLUSTER_PRIVATE_IP="$(ip -4 -o addr show dev eth1 | awk '{print $4}' | cut -d/ -f1)"

lua $SRC_DIR/config/kong-12f.lua $SRC_DIR/config/kong.yml.etlua $SRC_DIR
